module.exports = {
  "reviews": [
    {
      "id": 104,
      "rating": 4,
      "date": "2020-08-22T07:00:00.000Z",
      "review_header": "Monitored system-worthy solution",
      "username": "Celestino.Cremin25",
      "age_range": "45-54",
      "recommendationYN": "N",
      "purchased_for": "Friend",
      "review": "Totam ipsa iusto tempore ipsa. Ipsum voluptate odio ut. Voluptas molestias est. Deleniti similique vero fuga soluta et omnis nam aut neque. Vero voluptatem dicta praesentium tempore odit expedita. Natus porro inventore sapiente qui molestiae.",
      "upvotes": 4,
      "downvotes": 4,
      "play_experience": 1,
      "difficulty_level": 1,
      "money_value": null,
      "build_hrs": null,
      "build_mins": null,
      "building_experience": "Expert LEGO Builder",
      "pid": 1
    },
    // {
    //   "id": 220,
    //   "rating": 1,
    //   "date": "2020-08-05T07:00:00.000Z",
    //   "review_header": "Sharable well-modulated utilisation",
    //   "username": "Hyman96",
    //   "age_range": "25-34",
    //   "recommendationYN": "N",
    //   "purchased_for": "Son",
    //   "review": "Illum repellendus nihil soluta aut non eius id. Qui et facilis blanditiis magnam magni. Officia ex ab sed natus qui. Dolor vero reprehenderit possimus alias nulla numquam minima corrupti. Unde est ut repudiandae accusantium sit tempore neque.",
    //   "upvotes": 6,
    //   "downvotes": 0,
    //   "play_experience": 1,
    //   "difficulty_level": 2,
    //   "money_value": null,
    //   "build_hrs": null,
    //   "build_mins": 32,
    //   "building_experience": "Intermediate LEGO Builder",
    //   "pid": 1
    // },
    // {
    //   "id": 290,
    //   "rating": 3,
    //   "date": "2020-09-24T07:00:00.000Z",
    //   "review_header": "Face to face interactive flexibility",
    //   "username": "Danial74",
    //   "age_range": "19-24",
    //   "recommendationYN": "N",
    //   "purchased_for": "Self",
    //   "review": "Vitae iste sint animi ipsum pariatur numquam similique eligendi dolorum. Velit incidunt qui minima voluptatibus optio est ut. Non consequatur aperiam. Voluptatem reprehenderit ipsam rerum rerum est maiores earum rerum. Pariatur officiis sapiente minus quis illum dolores ea voluptatem nulla. Quo ducimus alias saepe.",
    //   "upvotes": 9,
    //   "downvotes": 4,
    //   "play_experience": null,
    //   "difficulty_level": 3,
    //   "money_value": null,
    //   "build_hrs": null,
    //   "build_mins": 13,
    //   "building_experience": "Novice LEGO Builder",
    //   "pid": 1
    // },
    // {
    //   "id": 373,
    //   "rating": 4,
    //   "date": "2020-08-25T07:00:00.000Z",
    //   "review_header": "Function-based uniform flexibility",
    //   "username": "Mona_Larson85",
    //   "age_range": "19-24",
    //   "recommendationYN": "N",
    //   "purchased_for": "Friend",
    //   "review": "Aperiam hic quam facere esse eum. Inventore quos id molestiae voluptate consequatur tempore. Voluptates quia et. Sed totam alias incidunt quisquam quas dolor nihil est eos. Accusantium est laborum labore id est eos accusantium earum distinctio.",
    //   "upvotes": 6,
    //   "downvotes": 2,
    //   "play_experience": null,
    //   "difficulty_level": null,
    //   "money_value": null,
    //   "build_hrs": null,
    //   "build_mins": 51,
    //   "building_experience": null,
    //   "pid": 1
    // },
    // {
    //   "id": 374,
    //   "rating": 4,
    //   "date": "2020-09-16T07:00:00.000Z",
    //   "review_header": "Phased asymmetric system engine",
    //   "username": "Jimmy_DuBuque",
    //   "age_range": "19-24",
    //   "recommendationYN": "N",
    //   "purchased_for": "Son",
    //   "review": "Et eius sint architecto consequatur maiores animi et. Autem earum eos rerum incidunt recusandae et. Dolorem qui totam et quis debitis cumque dicta repudiandae praesentium.",
    //   "upvotes": 10,
    //   "downvotes": 3,
    //   "play_experience": null,
    //   "difficulty_level": null,
    //   "money_value": null,
    //   "build_hrs": 3,
    //   "build_mins": null,
    //   "building_experience": "Intermediate LEGO Builder",
    //   "pid": 1
    // },
    // {
    //   "id": 490,
    //   "rating": 1,
    //   "date": "2020-09-24T07:00:00.000Z",
    //   "review_header": "Progressive 4th generation migration",
    //   "username": "Macey.Gibson14",
    //   "age_range": "35-44",
    //   "recommendationYN": "Y",
    //   "purchased_for": "Daughter",
    //   "review": "Neque ut omnis. Suscipit vel saepe eos vero. Laboriosam blanditiis earum quibusdam quod voluptatem quas ea quis voluptatem. Expedita eaque quia voluptate fuga similique numquam molestias. Facere eaque repellendus sunt voluptatem sequi voluptates mollitia.",
    //   "upvotes": 8,
    //   "downvotes": 1,
    //   "play_experience": null,
    //   "difficulty_level": null,
    //   "money_value": 4,
    //   "build_hrs": 4,
    //   "build_mins": 34,
    //   "building_experience": "Intermediate LEGO Builder",
    //   "pid": 1
    // },
    // {
    //   "id": 553,
    //   "rating": 1,
    //   "date": "2020-09-28T07:00:00.000Z",
    //   "review_header": "Ergonomic didactic model",
    //   "username": "Corine.Predovic71",
    //   "age_range": "14-18",
    //   "recommendationYN": "Y",
    //   "purchased_for": "Friend",
    //   "review": "Dolore voluptatem eius dicta distinctio ab. Temporibus laboriosam debitis illum molestiae ullam maxime. Nemo eaque incidunt id non non provident.",
    //   "upvotes": 6,
    //   "downvotes": 2,
    //   "play_experience": null,
    //   "difficulty_level": 4,
    //   "money_value": null,
    //   "build_hrs": null,
    //   "build_mins": 48,
    //   "building_experience": "Expert LEGO Builder",
    //   "pid": 1
    // },
    // {
    //   "id": 656,
    //   "rating": 4,
    //   "date": "2020-09-02T07:00:00.000Z",
    //   "review_header": "Enterprise-wide scalable emulation",
    //   "username": "Royal.Koepp",
    //   "age_range": "19-24",
    //   "recommendationYN": "N",
    //   "purchased_for": "Friend",
    //   "review": "Est cupiditate voluptatibus. Ut et facere est vel distinctio doloremque doloremque. Quidem dolorem et placeat incidunt. Aut illum possimus. Autem explicabo ab similique eius.",
    //   "upvotes": 9,
    //   "downvotes": 2,
    //   "play_experience": null,
    //   "difficulty_level": 1,
    //   "money_value": 2,
    //   "build_hrs": 2,
    //   "build_mins": 17,
    //   "building_experience": "Advanced LEGO Builder",
    //   "pid": 1
    // }
  ],
  "products": [
    {
      "pid": 1,
      "avg_score": 2.05,
      "total_reviews": 8,
      "recommendation_percentage": 25,
      "five_star": 0,
      "four_star": 4,
      "three_star": 1,
      "two_star": 0,
      "one_star": 3,
      "play_experience_avg": 1,
      "difficulty_level_avg": 2.2,
      "money_value_avg": 3,
      "five_star_percentage": 0,
      "four_star_percentage": 0.5,
      "three_star_percentage": 0.13,
      "two_star_percentage": 0,
      "one_star_percentage": 0.38
    }
  ]
}